# Generated by Django 4.2.3 on 2023-07-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefer_animals',
            field=models.CharField(choices=[('LA', 'Обожаю животных!'), ('IA', 'Зависит от животного'), ('NA', 'Предпочитаю поездки без животных')], default='IA', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefer_music',
            field=models.CharField(choices=[('LM', 'Включайте и погромче!'), ('IM', 'Все зависит от настроения - могу и спеть!'), ('NM', 'Предпочитаю тишину')], default='IM', max_length=2),
        ),
    ]
