# Generated by Django 4.2.3 on 2023-07-18 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_profile_prefer_animals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='base_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
