# Generated by Django 4.2.3 on 2023-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_from', models.TextField(verbose_name='Откуда')),
                ('point_to', models.TextField(verbose_name='Куда')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('spaces', models.IntegerField(verbose_name='Места')),
                ('empty_spaces', models.IntegerField(verbose_name='Свободные места')),
            ],
        ),
    ]
