# Generated by Django 4.2.3 on 2023-07-17 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_from', models.TextField(verbose_name='Населённый пункт откуда')),
                ('point_from', models.TextField(verbose_name='Откуда')),
                ('longitude_from', models.TextField(verbose_name='Долгота откуда')),
                ('latitude_from', models.TextField(verbose_name='Широта откуда')),
                ('locale_to', models.TextField(verbose_name='Населённый пункт куда')),
                ('point_to', models.TextField(verbose_name='Куда')),
                ('longitude_to', models.TextField(verbose_name='Долгота куда')),
                ('latitude_to', models.TextField(verbose_name='Широта куда')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('spaces', models.IntegerField(verbose_name='Места')),
                ('empty_spaces', models.IntegerField(verbose_name='Свободные места')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('in_process', models.BooleanField(default=False, verbose_name='Поездка а процессе')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершенная')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('passengers', models.ManyToManyField(blank=True, related_name='user_passengers', to=settings.AUTH_USER_MODEL, verbose_name='Пассажиры')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
    ]
