# Generated by Django 4.2.3 on 2023-07-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_base_user_alter_profile_prefer_animals_and_more'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='can_smoke',
            field=models.CharField(choices=[('LS', 'Можно курить'), ('IS', 'Можно курить, но не в машине'), ('NS', 'Курить нельзя')], default='IS', max_length=2, verbose_name='Можно ли курить'),
        ),
        migrations.AddField(
            model_name='trip',
            name='with_animals',
            field=models.CharField(choices=[('LA', 'Можно с животными'), ('IA', 'Наличие животных обсуждаемо'), ('NA', 'Без животных')], default='IA', max_length=2, verbose_name='Можно ли с животными'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver', to='users.profile', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='user_passengers', to='users.profile', verbose_name='Пассажиры'),
        ),
    ]
