# Generated by Django 4.2.3 on 2023-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AddField(
            model_name='trip',
            name='in_process',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='trip',
            name='latitude_from',
            field=models.TextField(default=1, verbose_name='Широта откуда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='latitude_to',
            field=models.TextField(default=1, verbose_name='Широта куда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='locale_from',
            field=models.TextField(default=1, verbose_name='Населённый пункт откуда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='locale_to',
            field=models.TextField(default=1, verbose_name='Населённый пункт куда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude_from',
            field=models.TextField(default=1, verbose_name='Долгота откуда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude_to',
            field=models.TextField(default=1, verbose_name='Долгота куда'),
            preserve_default=False,
        ),
    ]
