# Generated by Django 4.2.3 on 2023-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='can_smoke',
            field=models.CharField(choices=[('LS', 'Можно курить'), ('IS', 'Можно курить, но не в машине'), ('NS', 'Курить нельзя')], default='IS', max_length=2),
        ),
        migrations.AddField(
            model_name='trip',
            name='with_animals',
            field=models.CharField(choices=[('LA', 'Можно с животными'), ('IA', 'Наличие животных обсуждаемо'), ('NA', 'Без животных')], default='IA', max_length=2),
        ),
    ]
