# Generated by Django 4.2.3 on 2023-07-17 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_trip_can_smoke_trip_with_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(null=True, related_name='user_passengers', to=settings.AUTH_USER_MODEL, verbose_name='Пассажиры'),
        ),
    ]
