# Generated by Django 4.2.3 on 2023-07-18 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_prefer_animals_and_more'),
        ('trips', '0004_alter_trip_can_smoke_alter_trip_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver', to='users.profile', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='user_passengers', to='users.profile', verbose_name='Пассажиры'),
        ),
    ]
