# Generated by Django 4.2.3 on 2023-07-18 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_base_user'),
        ('trips', '0005_alter_trip_owner_alter_trip_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_driver', to='users.profile', verbose_name='Водитель'),
        ),
    ]
